#!/bin/bash

# I got rid of the just dependency to simplify.
# Using a bash script is enough for my purposes.

# TODO: Figure out why this build crashes because of zon_mod.
build() {
   zig build -Doptimize=ReleaseFast 
}

case "$1" in
    build) build;;
    debug) build;;
    run) zig build run -- "${@:2}";;
    fmt) zig fmt src;;
    lines) find src/ -type f ! -name '*.swp' -exec wc -l {} +;;
    test) zig test test.zig;;
    install)
        build
        cp zig-out/bin/y ~/.local/bin/y
        ;;
    *)
        echo Unknown argument "$1"
        exit 1
        ;;
esac
